# Generated by Django 3.1.7 on 2021-11-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
